
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame5;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Entry entry3;
	
	private global::Gtk.Button button15;
	
	private global::Gtk.Entry entry4;
	
	private global::Gtk.Label URL;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.Text = global::Mono.Unix.Catalog.GetString ("http://www.");
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.vbox4.Add (this.entry3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entry3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(4));
		// Container child vbox4.Gtk.Box+BoxChild
		this.button15 = new global::Gtk.Button ();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString ("Enviar");
		this.vbox4.Add (this.button15);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button15]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		w2.Padding = ((uint)(4));
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.HeightRequest = 286;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.vbox4.Add (this.entry4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entry4]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(4));
		this.GtkAlignment.Add (this.vbox4);
		this.frame5.Add (this.GtkAlignment);
		this.URL = new global::Gtk.Label ();
		this.URL.Name = "URL";
		this.URL.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>URL:</b>");
		this.URL.UseMarkup = true;
		this.frame5.LabelWidget = this.URL;
		this.Add (this.frame5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 558;
		this.DefaultHeight = 397;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
